### PR TITLE
Expand the third R assignment

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Merging for class. @brymz - I had added new exercises and modified existing ones. If you could update and add new solutions this morning that would be great.

**Comment by brymz** [comment]
I'm surprised to see you using `%>%` in `Dplyr-fix-code.md`. With the
simple solutions that I've been generating, I haven't used it at all. I
worry that it's a step into abstraction that might cause some problems with
understanding.

Do you want me to be using `%>%` for `dplyr` chains in code solutions
throughout?

**Comment by brymz** [comment]
Also, I'm missing the `shrub_volume_experiments_table.csv`.

**Comment by brymz** [comment]
Also, the link is broken in 'Scientific-0'. Should be '[Data Frames 1]({{ site.baseurl }}/exercises/Data-frames-1-R)'.

**Comment by ethanwhite** [comment]
> I'm surprised to see you using `%>%` in `Dplyr-fix-code.md`. With the simple solutions that I've been generating, I haven't used it at all. I worry that it's a step into abstraction that might cause some problems with understanding. 

I guess we're about to find out :)

Pipes have a long history in the shell and we teach them during novice shell in Software Carpentry. They have a lot of nice features and are rapidly becoming very popular in R and in particular in dplyr. I don't honestly think we could have not mentioned them because seeking help online would have been really confusing, but I'll have a better feel for how it went when we're doing exercises on Friday.

> Also, I'm missing the shrub_volume_experiments_table.csv... Fixed with #237 and a mysterious commit (ad87c39).

The mysterious commit is probably fine. The missing file was noticed at the beginning of class so I pushed to master to get it in quickly.

**Pull request merged**
