### PR TITLE
General cleanup of R-5 assignment

### PR DESCRIPTION
**Pull request by ethanwhite**
The major change is shifting Loops-3-R to using Bioconductor instead of manually parsing the fasta files.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Merging for class tomorrow.

@brymz - if you can update the answers by class time tomorrow I'd appreciate it as always.

**Comment by brymz** [comment]
From my read of the changed file, it looks like I will only have to update the output solution for Loops-3-R. Is that right?

**Comment by ethanwhite** [comment]
I think that's right.

**Comment by ethanwhite** [comment]
And, now that I think about it let's have them store the output in a data frame (I'm going to teach them how to do this today).

**Comment by ethanwhite** [comment]
I'll change the exercise, you change the solution.

**Comment by brymz** [comment]
Roger that.

**Comment by brymz** [comment]
I need to update my version of R to use `ShortRead`.

**Comment by ethanwhite** [comment]
> I need to update my version of R to use ShortRead.

The class is already all on the most recent version due to something from dplyr (I thought), so thanks for the heads up, but that should be OK.

**Comment by brymz** [comment]
Cool. I'll do my best to wrap up in 15 min. Do you want me to do the merge?

**Comment by ethanwhite** [comment]
Yeah, merge when ready.

**Comment by brymz** [comment]
> install.packages('ShortRead')
Warning in install.packages :
  package ‘ShortRead’ is not available (for R version 3.2.2)

Going to try version 3.2.1, next.

**Comment by brymz** [comment]
> Going to try version 3.2.1

Back on 3.2.2. After all of that it looks like I just used to wrong function call:
It's `biocLite("ShortRead")` not `install.packages("ShortRead")`

**Comment by ethanwhite** [comment]
Yeah, that's right. Glad you got it figured out.

**Pull request merged**
