### PR TITLE
Structure Readings with 2nd merge conflict resolved [from readings-2 branch]

### PR DESCRIPTION
**Pull request by brymz**
Follow-up from #278.
Closes #300

### CODE REVIEW

**Comment by brymz** [comment]
Your font-awesome patch works great! I think font-awesome and I are going to get along, nicely. 

Ready for merge!?

**Comment by ethanwhite** [comment]
Just tested again and it looks great. Everyone should be done with assignments for the semester so here... we... go.

**Comment by brymz** [comment]
Hurray! ...Is there an emoji for triumphant fist shaking?...

**Comment by ethanwhite** [comment]
There should be! Great job on this. That was definitely a lot of getting into the nitty-gritty of Jekyll/Liquid and it works great!

**Comment by brymz** [comment]
Totally. Thanks! It was a very fun and rewarding experience. I certainly learned a lot!!

**Pull request merged**
