### PR TITLE
Add 'R for Data Science' to Readings

### PR DESCRIPTION
**Pull request by brymz**
As per #446, #447, & #448

### CODE REVIEW

**Comment by ethanwhite** [comment]
Did you take a look at those alternatives and think they were better? That was my first impression but I didn't spend a lot of time comparing the options.

**Comment by brymz** [comment]
> Did you think those alternatives were better?

If by 'better' you mean 'more in-depth' then definitely. He does a really nice job of breaking up the concepts and introducing the package utility in a digestible manner. I learned a few things. There is definitely a bit more than we cover in our exercises. Our exercises are like word problems to his basic exercises. In the case of `dplyr` and `ggplot2`, I left the vignette references because they are more direct in their delivery of the function uses and might be easier for students to return to.

**Comment by ethanwhite** [comment]
I don't just mean 'more in-depth' because that could also mean too long or too detailed. So I guess what I'm asking for is your thoughts on whether these or the existing readings are a better introduction to the kinds of things (but not necessarily the specific functions) that we want the students to know. If you were taking the course and were to read one set of materials in each case, which one would you want it to be.

**Comment by brymz** [comment]
I think the 'R4DS' reading for `ggplot2` is a great introduction to the Hadleyverse. He writes it as the first coding chapter and I think it is the best resource we have for data visualization. As for `dplyr` and `tidyr`, I think the vignettes (that we used earlier) are sufficient and succinct resources for our students. Though I did learn interesting things by reading the 'R4DS' chapters, I think they are a bit verbose for our needs.

**Comment by ethanwhite** [comment]
OK, I've looked over things again and agree with you. Let's move this PR to switch out the `ggplot2` reading, keep the original readings for `dplyr` and `tidyr`, and maybe add a supplemental readings section to those readings pages and include the associated R4DS chapters (or add them parenthetically as supplemental or something along those lines).

**Comment by brymz** [comment]
> Let's move this PR to switch out the `ggplot2` reading, keep the original readings for `dplyr` and `tidyr`, and ...

I went with '*Optional Resources*'. Ready for review and merge.

**Pull request merged**
