### PR TITLE
Version control

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by brymz** [comment]
So if I understand this correctly, you've decided to teach Git from RStudio. Are these lessons translated from the git-1-R.md assignments? or made from scratch?

**Comment by ethanwhite** [comment]
Yes, and they are made from scratch since the others required a kind of
programming we don't focus on in Data Carpentry. I'm teaching these
tomorrow so any quick feedback would be appreciated.

Ethan

**Comment by ethanwhite** [comment]
Merging for class. Post merge review still appreciated (especially if it comes with fixes :smile:).

**Comment by ethanwhite** [comment]
I just fixed the mismatch between title numbers and file name numbers.

**Pull request merged**
