### PR TITLE
Add short lecture on making sure code runs

### PR DESCRIPTION
**Pull request by ethanwhite**
Discuss how to make sure code runs to help reinforce key points about reproducibility early and decrease the number of issues with grading.

### CODE REVIEW

**Comment by ethanwhite** [comment]
I think this is probably a valuable addition for Friday if you have time, but see what you think.

**Comment by KristinaRiemer** [comment]
Is there a way to look at the website with these changes, or does that only work locally?

**Comment by KristinaRiemer** [comment]
I'm not going to merge this until after class today, just so the website doesn't change during class and put people off-kilter.

**Comment by ethanwhite** [comment]
:+1:

**Pull request merged**
