### PR TITLE
Update JOIN file names and content

### PR DESCRIPTION
**Pull request by brymz**
As per #481 & #482

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @brymz!

**Comment by brymz** [comment]
This is ready to go.

One comment / clarification on `Advanced-queries-detailed-join.md`:

> Be sure to choose only rodents and exclude individuals that have not been identified to genus.

My solution to this statement is `WHERE taxa='Rodent' AND  species_id!='UR'`. 

- [ ] That's ok. That's what I expected.
- [ ] Add clarification to exercise to encourage this solution.
- [ ] Add other clarification (like `WHERE genus IS NOT NULL`) and revise solution accordingly.
- [ ] Remove this condition from the exercise and solution.

**Comment by ethanwhite** [comment]
I agree it's unclear and don't have strong feelings about the right solution. I guess in hindsight I'd actually prefer it to be "identified to species" with a `species_id <> 'sp.'`. If we change that I'll need to get them anyone who's finished with it to update their answer, but in all likelihood most of them won't have done it yet anyway.

**Comment by brymz** [comment]
I'm unfamiliar with the `<>`.

**Comment by ethanwhite** [comment]
`<>` is technically the SQL standard for not equals. See https://en.wikipedia.org/wiki/SQL. That said, almost all databases also accept `!=`, and since that's what it is in R there's probably an argument for teaching `!=` instead.

**Comment by brymz** [comment]
That's a game changer. Needless to say all of my solutions use `!=`. We might consider putting something about this in `materials/sql-basic-queries/`. I'll get started on the exercise and solution revision.

**Comment by ethanwhite** [comment]
I generally show them both, so it's certainly not a big deal to stay with `!=`. Agree that we should explicitly introduce `not equals` in `sql-basic-queries`. What do you think about mentioning both but stating that we'll focus on `!=` since it's consistent with other languages.

**Pull request merged**
