### PR TITLE
Exercise yaml revision

### PR DESCRIPTION
**Pull request by brymz**
As per #388.

### CODE REVIEW

**Comment by brymz** [comment]
Let me try and explain. This branch is roughly item 1 in #388. 

In checking file names and `yaml`, it became clear that `exercises/` required a merge of the various remnants of the previous versions of the course. The commits are largely individual file name changes and `yaml` additions/updates of subtitles and language. In other words, this PR brings up to date the file names and `yaml` for all of the files in `exercises/`. File names take the form of `title`-`language`.md . `subtitles` were simplified to remove punctuation and excess words.

**Comment by brymz** [comment]
The PR is now up to item 3 in #388. I have automated the `yaml` changes and am checking back on `topic`s and `title`s. I have the SQL `exercises/` left to do.

**Comment by brymz** [comment]
@ethanwhite, This is a good early spot for review.

1) Have a look at any `exercise.md` example to see how I've restructured the `yaml`. The new file name will have the structure `topic`-`title`-`language`.md.

2) Run the site locally from this branch and check out `exercises/index`. Browse through to review `topic` and `title` choices. 
   - Are the `topics` good groupings? This should be straight forward because most of the `topic` were drawn right from the `old_title`. 
   - Are the `title` sufficiently descriptive? There should be no duplicate `title` within a language. The `topic` may help add clarity to the `title`.

**Comment by brymz** [comment]
Completed:

1) Check exercise/ title and subtitle for naming: group & unique names, accurate ordering, capitalization, no punctuation except `-`.

2) Rename title to `old_title` as placeholder.

3) Update yaml tags: `old_title` -> `topic`, `subtitle` -> `title`.

4) Update assignments/ lists: `old_title` -> `title`.

**Comment by brymz** [comment]
Completed tasks:

5) Rename exercise/, output/, datacarp-semester-biology-solns files. 
- solution files PR: https://github.com/weecology/datacarp-semester-biology-exercise-solns/pull/104

6) Update 'follow-up' links.

7) Remove old_title.

**Comment by brymz** [comment]
Completed the final task for #388: update site formatting. The PR could be ready to go, except for some special case issues I noticed in a brief self review:
- Automation missed `Sql-` `solutions/` file names
- follow-up link in `R-sql-connect-and-query-R.md`

**Comment by brymz** [comment]
I made a sweep behind my automaton to clean up any bad file names and broken links. I also updated the `docs/` for the new exercise structure.

This PR is ready for review!

**Comment by ethanwhite** [comment]
Thanks @brymz and sorry for being so slow on this. I've given it a light read through and everything looks great. It's so major that I'm not going to try to get through it line by line, so I'm going to go ahead and merge and we'll come back and clean up any little issues that end up sneaking through.

**Pull request merged**
