### PR TITLE
mv .ipynb to materials/; mv python lecture data to data/

### PR DESCRIPTION
**Pull request by brymz**
As per #421.

I think that the `.IPYNB` that link to the relocated data files will require edits of the file path.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Let's go ahead and handle checking and fixing any need to update data file links as part of this PR so that things don't get out of sync.

**Comment by brymz** [comment]
I updated the data file links... and some other things happened.

- I updated my machine to Python 3 and installed iPython Notebooks. The new software did not play nice with the out-dated versions of `ipynb`. I was not able to figure out how to connect the `ipynb` to a working `kernel`. This meant that I could not run any of the code cells for testing or get new output cells.  I tested changes to the data file paths and code with a `New` `ipynb`.
- Opening the old `ipynb` in the new software automatically updated the `ipynb` to v4.
- I updated `print()` to Python3 for the few files with broken file paths. 

This PR could be ready to merge... or given the status update, could launch an effort to update all of the Python material.

**Comment by ethanwhite** [comment]
The notebooks work fine for me in a current version of Jupyter. I open them, they get converted, and then the execute as expected.

How did you install the notebook? It seems like there's a problem with your install that we should get fixed so that you can check all of these if we're going to keep them.

**Comment by brymz** [comment]
I installed Anaconda and then `jupyter notebook`.

**Comment by ethanwhite** [comment]
1. Mac or PC?
2. What does running `which python` and `which jupyter` from the command line generate?

**Comment by brymz** [comment]
MAC OS X Yosemite V 10.10.5
`which python` - `//anaconda/bin/python`
`which jupyter` - `//anaconda/bin/jupyter`

**Pull request merged**
