### PR TITLE
Remove numbers from R exercise titles

### PR DESCRIPTION
**Pull request by brymz**
As per #506.

We may consider this update for 'aftersemester'.

### CODE REVIEW

**Comment by brymz** [comment]
This task is complete for all R exercises and ready for review. 

Python and Access exercises can get updated along with #145.

**Comment by ethanwhite** [comment]
I really like this. What's the argument for waiting until the end of the semester?

**Comment by brymz** [comment]
> What's the argument for waiting until the end of the semester?

It was more of a caution that the name and link was modified for a number of the exercises in the previous assignments (`r-intro` & `r-data`). I wasn't sure if that was going to affect the course.

**Comment by ethanwhite** [comment]
As long as the links on the site all still end up in the same place that should be fine. I don't think most folks are writing down the raw links. If that makes sense to you I'll go ahead and merge.

**Comment by brymz** [comment]
And they are referencing exercises by `Problem #` not `Title`. If that's right, good to merge.

**Comment by ethanwhite** [comment]
When turning in assignments you mean?

**Comment by brymz** [comment]
Yes.

**Pull request merged**
