### PR TITLE
Issue 902: Change data file names to lower case

### PR DESCRIPTION
**Pull request by amitkumardeol**
Updated file names lower casing for following files from data file system:

- MOMv3.3.txt
- NEON-airborne.zip
- Portal-plots.csv
- Portal-species.csv
- Portal-plots-original.csv
- Portal-species-original.csv
- SJER_dtmCrop.tif
- SJER_dsmCrop.tif
- HARV-NDVI.zip
- SJER-NDVI.zip
- Ramesh2010-macroplots.csv
- HARV_034subplt.csv
- HARV_dtmCrop.tif
- HARV_dsmCrop.tif
- A-saccharovorans.fasta
- C-aenigmarchaeum.fasta
- C-lagunensis.fasta
- C-symbiosum.fasta
- F-fontis.fasta
- G-acetivorans.fasta
- H-salinum.fasta
- N-moolapensis.fasta
- T-pendens.fasta

Updated the code which uses file path references to import the impacted files.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Hi @amitkumardeol - thanks so much for contributing to the project! I see you're still pushing some commits, so just let me know when you're ready for review, or if you're running into any issues, and I'll be happy to help as soon as your ready.

**Comment by amitkumardeol** [comment]
@ethanwhite Build is failing for failed test. although it looks like links do exist still failing the test. Can you help me in fixing build error?

**Comment by ethanwhite** [comment]
Sorry about that (and for the delay). I'll take a look as soon as I can and let you know what I see.

**Comment by ethanwhite** [comment]
Apologies again for the delay (the end of the semester in 2020 turns out to be even more out of control that the end of the semester usually is).

You're right that the build test failure was independent of this.

I squashed the commits, made a couple of small fixes due to the most common source of the file not allowing the for changes to lower case, fixed the merged conflict, and just merged this in in e9d7e981034dd4e28817c4137378da4b4c1335cb.

Thanks so much for your contribution. You're welcome here any time you want to help out.

**Pull request closed without merging**
