### PR TITLE
Add Lecture Notes Content to Assignment Page

### PR DESCRIPTION
**Pull request by brymz**
As per #524.

BUG REPORT: The 'Lecture Notes' section on `semester-biology/assignments/sql-intro/`, `r-fundamentals-2`, `r-spatial`, `r-git`, and `r-sql`  does not process liquid tags, which breaks the links `{{ site.baseurl }}/...`. This is not a problem on the other `assignments/` pages. I'm head-bashing right now why some and not the others, so any thoughts would be helpful.

Copying one of the files that works and putting it in place of one that doesn't work made no difference.

### CODE REVIEW

**Comment by ethanwhite** [comment]
No idea I'm afraid.

So this is WIP at the moment?

**Comment by brymz** [comment]
I think I've got it figured out. Capitalization seems to work. Just putting it together, now.

**Comment by brymz** [comment]
Ok. This is ready for a review.
I am looking for feedback on link functionality and page formatting.

**Comment by ethanwhite** [comment]
This all looks great to me. I won't merge since it's still marked WIP, but if you're happy I think this is ready to go.

**Pull request merged**
