### PR TITLE
Integrated NEON Probelm

### PR DESCRIPTION
**Pull request by brymz**
As per #230.

'NEON 1' uses small mammal trapping data I pulled from data.neoninc.org and responds more directly to your issue request.

'NEON 2' is currently a stub. The exercise uses LiDAR data provided as a raster file from neondataskills.org and follows-up on the [Canopy Height Model lesson](http://neondataskills.org/lidar-data/lidar-data-rasters-in-R/). Are you interested in me continuing to develop this exercise?

My hours are up for this week, but I'm just a couple hours from wrapping up. I could bank a couple hours for next week if you want to see any of this done this week.

### CODE REVIEW

**Comment by ethanwhite** [comment]
whatever works best for you timing wise is fine with me.

**Comment by brymz** [comment]
'Neon 1': COMPLETE

**Comment by brymz** [comment]
Exercises 1 & 2 Complete and ready for review.

'NEON 2' was a challenge to integrate with the neondataskills.org tutorial. It is a bit advance by nature than other exercises in 'Programming for Biologists'. I chose the exercise tasks to work with modifying existing code and improve familiarity with 'dplyr', 'ggplot2', but there are certainly other directions that the exercise can go.

**Comment by ethanwhite** [comment]
Thanks @brymz. I'm going to go ahead and merge these I'll and think more about whether to tweak 2 when I have a little more time.

**Pull request merged**
