### PR TITLE
Clean materials/

### PR DESCRIPTION
**Pull request by brymz**
545d76f as per #488 title.

Remaining work as per #488 comments.

### CODE REVIEW

**Comment by brymz** [comment]
So, what's happening here?

#488 reminded me that `materials/` was the remaining location that had not fully integrated and updated the 'Programming for Biologists' materials with 'Data Carpentry for Biologists'. I am going through all of the materials to: 

* add links to the `materials/index`
* make sure front matter is sufficient for rendering  
* move script files to `code/`
* remove blatantly out-dated files

My hope is that the remaining files will be presentable and accessible from `materials/index` for you (@ethanwhite) to quickly go through and propose other deletions or merges.

**Comment by brymz** [comment]
Ok. This is ready for a review.

There is definitely some room to shed some extraneous/duplicate lecture material. I have tried to group those files to make it easy to compare and choose. Likely, the greatest set of dismissals will come from the **Extra Notes** sections that include materials that didn't line up with the previous **Course Notes** structure. I do think some of these materials remain useful, but definitely for instructors or intermediate-expert users that are looking for a reference.

If we were to set this aside for a while, the pieces of immediate concern for #488 are:

* 545d76f
* fix 'Project Decomposition' and 'Version Control' links (i.e., `decomposition-R`)
* add `projects.md` link
* move `R` scripts to `code/` and update links in `debugging-R.md`

**Comment by ethanwhite** [comment]
This all looks good. I'd also recommend getting rid of:

* Debugging Example 'Overkill' Solution
* Functions (Similar Alternate)
* Installing `nose` on Windows
* Scientist's Python Inferno

**Comment by brymz** [comment]
Removed extra files and links.

**Pull request merged**
