### PR TITLE
Versions-control-basics format ordered lists

### PR DESCRIPTION
**Pull request by brymz**
As per #270. I chose to use numbered lists.

### CODE REVIEW

**Comment by ethanwhite** [comment]
The issue with numbered lists here is that students interpret them as being sub-problems since that's how they are used in most exercises. I recall that we talked about using numbered lists for actual sub-problems and something else for lists of instructions, but don't recall what that 'something else' was.

The use of `1\.` is intentional because otherwise the code blocks will prevent the numbers from properly rendering in order.

**Comment by brymz** [comment]
I also recall a conversation about numbered lists. I believe it was regarding a problem like 'basic-2-R.md' where the tasks are presented without an expectation for what order they are performed, and use `*`. I don't remember a conclusion regarding step-wise problems. I have been numbering step-wise problems, like `Sql-importing-data.md`. I would say that in some ways each step in the exercise is like a sub-problem. It just doesn't have a tangible output. Is the trouble that it isn't always obvious if there's supposed to be output?  

> The use of 1\. is intentional.

Ok. I'll have to go back and make sure the indenting is properly formatted.

**Comment by brymz** [comment]
> > The use of 1. is intentional.
> Ok. I'll have to go back and make sure the indenting is properly formatted. 

I set the code blocks into the list by indenting each line in the code block three spaces. The list should now render in order and maintain consistent indent formatting with the rest of the assignment.

**Comment by ethanwhite** [comment]
> I set the code blocks into the list by indenting each line in the code block three spaces. The list should now render in order and maintain consistent indent formatting with the rest of the assignment.

Wow, that's a new one for me. Thanks!

> Is the trouble that it isn't always obvious if there's supposed to be output? 

Yeah, I've seen students get hung up on this, but since we've been doing it this way already let's go ahead and put this in and we can always revisit later.

**Pull request merged**
