### PR TITLE
Create new followup climate space exercise, with solutions

### PR DESCRIPTION
**Pull request by KristinaRiemer**
Okay, here's the first version of the new exercise. I'll also be submitting a PR for the solution in a second. 

Should it go between the current third (Nested Functions) and fourth (Choice Operators) exercises for this week?

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks great. Should the order of 1 & 2 be reversed since they need to first get the data and then plot it?

**Comment by ethanwhite** [comment]
I'll add it into the assignment once it's merged since I'm changing some other things in the assignment right now.

**Comment by KristinaRiemer** [comment]
I figured having them do the plotting function first because it's easier? And it's realistic to refactor different parts of the code at different times, not necessarily in order. I'm happy to switch them around though.

**Comment by ethanwhite** [comment]
I totally get where you're coming from, but I suspect that the out of order refactoring will confuse novices so let's go with the natural data -> plot order.

**Comment by ethanwhite** [comment]
Awesome! Thanks. In it goes.

**Pull request merged**
