### PR TITLE
Numbered files

### PR DESCRIPTION
**Pull request by brymz**
Reset #356 
---
As per #352.

Minor unrelated changes: 9c0536b, f7a4945, d95ec34, 4f7d14a

### CODE REVIEW

**Comment by ethanwhite** [comment]
Still has merge conflicts unfortunately.

**Comment by brymz** [comment]
Yep. Had to go backwards to make a second attempt.

**Comment by brymz** [comment]
TA - DA!

**Comment by ethanwhite** [comment]
Nice. So this is just the same PR I already reviewed without the conflict, yes?

**Pull request merged**
