### PR TITLE
R capstone updates

### PR DESCRIPTION
**Pull request by ethanwhite**
Add three new integration exercises and include in the capstone week.

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
Should there be a rubric or something for the style exercise, or do you think they'll be able to figure out most of the fixes?

**Comment by KristinaRiemer** [comment]
Or maybe a rubric of what's expected for the all the exercises for the week? Just correct order, lines not too long, everything possible in functions.

**Comment by ethanwhite** [comment]
I think a rubric of some kind is a great idea, but I don't personally have time to add one (still not ready to walk into class yet).

**Comment by KristinaRiemer** [comment]
I can add it as an issue for next year, if you want?

**Pull request merged**
