### PR TITLE
Minor revisions to main repo found during template development.

### PR DESCRIPTION
**Pull request by brymz**
As per #377.

### CODE REVIEW

**Comment by brymz** [comment]
This is ready for review. I had considered revising `syllabus.md` to `site.baseurl` and `site.email`, but thought you might want to print the syllabus from its text file before rendering.

**Comment by brymz** [comment]
I revised `syllabus.md` to include yaml `site` and `page` tags. Now, all of the class-specific information is stored in the front matter.

**Comment by ethanwhite** [comment]
Looks really good overall. I love how you handled generalizing the syllabus.

The one thing I noticed is that `START-for-self-guided-students.md `, `audience.md`, and `contributing.md` now point to the course site instead of the central site and I'm wondering what we actually want there. My initial reaction is that feedback and contributions are best directed to the main repo, but I'm certainly open to discussion on this.

**Comment by brymz** [comment]
Thanks!

It was also unclear to me what was the best approach for repo links. In my mind, feedback can be described as relating to course material or site functionality. For the main repo, feedback goes to the same place. But maybe that shouldn't be the case for forked repos. I think `START-for-...-students.md` can always be described as course material and directed to `{{ site.github.repo }}`. Perhaps, `audience.md` and `contributing.md` could use a revision (and maybe an `{% if %}`) to separate out the two types of feedback. 

There might already be a merge conflict with #417. I would prefer to get this in and then resolve conflicts and address the repo links issue there.

**Comment by ethanwhite** [comment]
Sounds good. Done.

**Pull request merged**
