### PR TITLE
add Style-R.md and BADstyle-R.R code

### PR DESCRIPTION
**Pull request by brymz**
As per #298.

### CODE REVIEW

**Comment by ethanwhite** [comment]
My first thought is that it would be nice for this to be a science/biology related example so that the thought process from the code they've been writing (and to the code they will write) transfers a little better. What do you think?

**Comment by brymz** [comment]
I guess I saw this lesson in a similar fashion as the 'Expressions and Variables' and 'Vectors' exercises, where the concepts are fundamental beyond working with data. My goal was to develop a lesson that was a stand alone script (i.e., no download or working directory requirements) that I could guarantee would open and work despite the formatting issues.

Are you opposed to the 8-ball example broadly or just the delivery? Are simulations beyond the scope of 'data science'? I could easily make the `answers` a data file to `read.csv()`. My other thought was to pick an existing exercise where I could poorly format the solution, but then the solution would be out there for grabs.

**Comment by ethanwhite** [comment]
I agree that the concepts go beyond working with data, but that could be said of a lot of what's in this course. Since this is coming at the end of the course there is no need to keep thinks simple like in the early exercises, so it seems like keeping this in the biology data realm would be inherently beneficial.

**Comment by brymz** [comment]
Simulate population time series or sequences.

**Comment by ethanwhite** [comment]
I'm going to go ahead and close this since presumably the eventual solution will be in a new PR. If I'm wrong about that feel free to reopen.

**Pull request closed without merging**
